name: build for windows and android

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Extract app version
        run: |
          $VERSION = Select-String -Path "pubspec.yaml" -Pattern "^version:" | ForEach-Object { ($_ -split ":")[1].Trim() } | ForEach-Object { ($_ -split "\+")[0] }
          echo "APP_VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: install dep
        run: flutter clean && flutter pub get && flutter pub run flutter_launcher_icons

      - name: build windows
        run: flutter build windows

      - name: build android
        run: flutter build apk

      - name: Create and push git tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a "v${{ env.APP_VERSION }}" -m "Release v${{ env.APP_VERSION }}"
          git push origin "v${{ env.APP_VERSION }}"

      - name: Package Windows build
        run: |
          Compress-Archive -Path "build/windows/x64/runner/Release/" -DestinationPath "eureka_win.zip"

      - name: Upload windows build files
        uses: actions/upload-artifact@v3
        with:
            name: eureka_win
            path: build/windows/x64/runner/Release/

      - name: Upload android build files
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
