name: build for mac

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: install dep
        run: flutter clean && flutter pub get && flutter pub run flutter_launcher_icons

      - name: build macos
        run: flutter build macos

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: eureka_mac
          path: build/macos/Build/Products/Release/eureka.app
          retention-days: 1
