name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'

      - name: install dep
        run: flutter clean;flutter pub get;flutter pub run flutter_launcher_icons

      - name: build apk
        run: flutter build apk --release

      - name: Upload APK
        run: |
          curl -v \
            -H "Authorization: Bearer $API_TOKEN" \
            -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
            https://dl.aextoxicon.site/upload
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
