name: build for mac

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Extract app version
        run: |
          VERSION=$(grep -E "^version:" pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: install dep
        run: flutter clean && flutter pub get && flutter pub run flutter_launcher_icons

      - name: build macos
        run: flutter build macos

      - name: Create and push git tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a "v${{ env.APP_VERSION }}" -m "Release v${{ env.APP_VERSION }}"
          git push origin "v${{ env.APP_VERSION }}"

      - name: Zip built app
        run: |
          zip -r -X eureka_mac.zip build/macos/Build/Products/Release/eureka.app

      - name: Create GitHub Release and upload app
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.APP_VERSION }}
          name: Release v${{ env.APP_VERSION }}
          files: eureka_mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}