name: build for windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'

      - name: install dep
        run: flutter clean && flutter pub get && flutter pub run flutter_launcher_icons

      - name: build windows
        run: flutter build windows

      - name: Upload Windows zip
        env: 
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer $API_TOKEN" -F "file=@build/windows/runner/x64/Release/auto_wifi.zip" https://update.aextoxicon.site/upload

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto_wifi_win
          path: build/windows/x64/runner/Release/
