name: build for mac

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.35.4"

            - name: install dep
              run: flutter clean && flutter pub get && flutter pub run flutter_launcher_icons

            - name: build macos
              run: flutter build macos

            - name: Upload macos zip
              env: 
                  API_TOKEN: ${{ secrets.API_TOKEN }}
              run: |
                zip -r -X auto_wifi_mac.zip build/macos/Build/Products/Release/auto_wifi.app
                curl -X POST -H "Authorization: Bearer $API_TOKEN" -F "file=@auto_wifi_mac.zip" https://update.aextoxicon.site/upload
