name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          cache: true

      - name: 缓存 Flutter 依赖 (Windows)
        uses: actions/cache@v4
        with:
          path: ${{ env.pub-cache }} 
          key: ${{ runner.os }}-flutter-${{ steps.setup-flutter.outputs.flutter-version }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ steps.setup-flutter.outputs.flutter-version }}-
            ${{ runner.os }}-flutter-

      - name: install dep
        run: flutter pub get;flutter pub run flutter_launcher_icons

      - name: build apk
        run: flutter build apk --release

      - name: build windows
        run: flutter build windows

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
